## 6-е домашнее задание - Библиотека numpy

<b>Срок до 2 июня 2022г. (включительно)</b>

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring_Python_2022</b>» в github в папку "<b>homework-6</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
import numpy as np

b = np.linspace(-1.3, 2.5, 64)

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
np.tile([1, 2, 3], 6)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [5]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
a = np.zeros((10, 10))
a[:, 0] = 1
a[:, -1] = 1
a[0, :] = 1
a[-1, :] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [8]:
a = np.zeros((8, 8))
a[0::2, 0::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [9]:
def matrix(n):
    return [[i + j for i in range(n)] for j in range(n)]

matrix(5)

[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [2, 3, 4, 5, 6],
 [3, 4, 5, 6, 7],
 [4, 5, 6, 7, 8]]

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
print(np.dot(a, b)) 
print(np.dot(a, c)) 
print(np.vdot(c, d))

[[22 28]
 [49 64]]
[14 32]
32


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [13]:
a = np.cos(np.arange(0, 1, 0.05))
b = np.sin(np.arange(0, 1, 0.05))
c = np.append(a, b).reshape((2, len(a)))
c

array([[1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
        0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
        0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
        0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309],
       [0.        , 0.04997917, 0.09983342, 0.14943813, 0.19866933,
        0.24740396, 0.29552021, 0.34289781, 0.38941834, 0.43496553,
        0.47942554, 0.52268723, 0.56464247, 0.60518641, 0.64421769,
        0.68163876, 0.71735609, 0.75128041, 0.78332691, 0.8134155 ]])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [14]:
np.random.randint(-1, 3, (3, 5))

array([[ 2, -1,  0,  2,  2],
       [-1,  0,  1,  1, -1],
       [-1,  0,  1,  0,  0]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [ ]:
a.sum()
a.sum(axis=1)
a.sum(axis=0)
a.mean(axis=1)
a.var(axis=1)
a.std(axis=1)

11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = (a[0, :] - (a.mean(axis=1))[0]) / (a.std(axis=1))[0]
c = (a[1, :] - (a.mean(axis=1))[1]) / (a.std(axis=1))[1]
a = np.append(b, c).reshape((2, 3))
a

array([[-1.22474487,  0.        ,  1.22474487],
       [-1.22474487,  0.        ,  1.22474487]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [16]:
a = np.array([[1, 5, 2], [3, 4, 5], [5, 6, 1]])
third = a[:, 2]
ind = np.argsort(third)
a[ind, :]

array([[5, 6, 1],
       [1, 5, 2],
       [3, 4, 5]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [17]:
a = np.random.randint(-1, 3, (3, 5))
b = np.dot(a.T, a)
c = np.dot(a, a.T)
b, c
# Матрицы разные по размеру: b 5x5, c 3x3. Обе квадратные.

(array([[ 3,  0, -1,  0,  2],
        [ 0,  2,  0,  0,  0],
        [-1,  0,  3,  0, -2],
        [ 0,  0,  0,  0,  0],
        [ 2,  0, -2,  0,  2]]),
 array([[ 4, -2,  0],
        [-2,  4,  0],
        [ 0,  0,  2]]))

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [18]:
a = np.random.randint(-1, 3, (3, 5))
b = np.dot(a.T, a)
c = np.dot(a, a.T)
np.sum(np.diagonal(b)), np.sum(np.diagonal(c))

(21, 21)

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [20]:
a = np.random.randint(-1, 3, (3, 3))
b = np.dot(a.T, a)
c = np.dot(a, a.T)
print(np.linalg.det(a))
print(np.linalg.matrix_rank(a))
print(np.linalg.det(b))
print(np.linalg.matrix_rank(b))
print(np.linalg.det(c))
print(np.linalg.matrix_rank(c))

0.0
2
0.0
2
0.0
2


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [21]:
np.random.seed(1032196529)
np.random.randint(10)

6

In [23]:
def f(x):
    return (np.cosh(3 * x)) ** 2

def right_rect(a, b, h, f):
    k = int((b - a) / h)
    x = np.linspace(a, b, k)
    result = np.sum(f(x)[1:]) * h
    return result

def left_rect(a, b, h, f):
    k = int((b - a) / h)
    x = np.linspace(a, b, k)
    result = np.sum(f(x)[:len(x)]) * h
    return result

def solve1_1(a, b, h, f):
    i = 1
    while (abs(right_rect(a, b, h / 10, f)) - abs(right_rect(a, b, h, f))) > 0.00001:
        h /= 10
        i += 1
    return right_rect(a, b, h, f), i

def solve1_2(a, b, h, f):
    i = 1
    while (abs(left_rect(a, b, h, f)) - abs(left_rect(a, b, h / 10, f))) > 0.00001:
        h /= 10
        i += 1
    return left_rect(a, b, h, f), i

def trapezoid(a, b, h, f):
    k = int((b - a) / h)
    x = np.linspace(a, b, k)
    result = ((f(x)[0] + f(x)[-1]) / 2 + np.sum(f(x)[1:len(x) - 1])) * h
    return result

def solve2(a, b, h, f):
    i = 1
    while (abs(trapezoid(a, b, h / 10, f)) - abs(trapezoid(a, b, h, f))) > 0.00001:
        h /= 10
        i += 1
    return trapezoid(a, b, h, f), i

def simp(a, b, h, f):
    k = int((b - a) / h)
    x = np.linspace(a, b, k)
    result = (f(x)[0] + f(x)[-1] + 2 * np.sum(f(x)[2:len(x) - 1:2]) + 4 * np.sum(f(x)[1:len(x) - 1:2])) * (h / 3)
    return result

def solve3(a, b, h, f):
    i = 1
    while (abs(simp(a, b, h / 10, f)) - abs(simp(a, b, h, f))) > 0.00001:
        h /= 10
        i += 1
    return simp(a, b, h, f), i

print(solve1_1(0, 1 / 3, 0.1, f))
print(solve1_2(0, 1 / 3, 0.1, f))
print(solve2(0, 1 / 3, 0.1, f))
print(solve3(0, 1 /3, 0.1, f))

(0.4689038489169453, 6)
(0.4652638162949438, 1)
(0.4689031583680225, 6)
(0.4689031583671157, 6)
